import React, { useState, useMemo } from 'react';
import {
  Clock,
  ShieldCheck,
  ShieldAlert,
  CheckCircle2,
  Sparkles,
  RotateCw,
  Search,
} from 'lucide-react';
import { PageHeader } from '../components/layout/PageHeader';
import { SearchInput } from '../components/ui/SearchInput';
import { Select } from '../components/ui/Select';
import { Skeleton } from '../components/feedback/Skeleton';
import { ErrorState } from '../components/feedback/ErrorState';
import { useRecommendations } from '../hooks/useRecommendations';
import { useMediaQuery } from '../hooks/useMediaQuery';
import {
  RecommendationTable,
  RecommendationCard,
  RecommendationDrawer,
} from '../features/recommendations';
import { formatCurrency } from '../lib/formatters';

const STATUS_META = [
  { key: 'all', label: 'All', icon: Sparkles, color: 'text-accent bg-accent/10 border-accent/20' },
  { key: 'PENDING', label: 'Pending', icon: Clock, color: 'text-warning bg-warning/10 border-warning/20' },
  { key: 'APPROVED', label: 'Approved', icon: ShieldCheck, color: 'text-success bg-success/10 border-success/20' },
  { key: 'REJECTED', label: 'Rejected', icon: ShieldAlert, color: 'text-critical bg-critical/10 border-critical/20' },
  { key: 'APPLIED', label: 'Applied', icon: CheckCircle2, color: 'text-info bg-info/10 border-info/20' },
];

const CATEGORY_OPTIONS = [
  { value: 'all', label: 'All Categories' },
  { value: 'RIGHTSIZING', label: 'Rightsizing' },
  { value: 'STORAGE_TIER', label: 'Storage Tier' },
  { value: 'ARCH_MODERNIZATION', label: 'Arch Modernization' },
  { value: 'SAVINGS_PLAN', label: 'Savings Plan' },
  { value: 'NETWORKING', label: 'Networking' },
  { value: 'COMPUTE', label: 'Compute' },
];

const RISK_OPTIONS = [
  { value: 'all', label: 'All Risk Levels' },
  { value: 'LOW', label: 'Low Risk' },
  { value: 'MEDIUM', label: 'Medium Risk' },
  { value: 'HIGH', label: 'High Risk' },
];

const PAGE_SIZE = 8;

export default function RecommendationsPage() {
  const [filters, setFilters] = useState({
    status: 'all',
    category: 'all',
    risk: 'all',
    search: '',
  });
  const [page, setPage] = useState(1);
  const [selectedRec, setSelectedRec] = useState(null);
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  const isMobile = useMediaQuery('(max-width: 767px)');

  const { data: allRecs = [], isLoading, isError, refetch, isFetching } = useRecommendations({});

  // Client-side filter + search
  const filtered = useMemo(() => {
    return allRecs.filter((rec) => {
      if (filters.status !== 'all' && rec.status !== filters.status) return false;
      if (filters.category !== 'all' && rec.category !== filters.category) return false;
      if (filters.risk !== 'all' && rec.riskLevel !== filters.risk) return false;
      if (filters.search) {
        const q = filters.search.toLowerCase();
        if (
          !rec.title.toLowerCase().includes(q) &&
          !rec.id.toLowerCase().includes(q) &&
          !(rec.resourceName || '').toLowerCase().includes(q) &&
          !(rec.service || '').toLowerCase().includes(q)
        ) return false;
      }
      return true;
    });
  }, [allRecs, filters]);

  // Status counts (from full unfiltered list)
  const statusCounts = useMemo(() => {
    const counts = { all: allRecs.length };
    for (const rec of allRecs) {
      counts[rec.status] = (counts[rec.status] || 0) + 1;
    }
    return counts;
  }, [allRecs]);

  // Total potential savings from filtered list
  const totalSavings = useMemo(
    () => filtered.reduce((sum, r) => sum + (r.monthlySavings || 0), 0),
    [filtered]
  );

  const handleRowClick = (rec) => {
    setSelectedRec(rec);
    setIsDrawerOpen(true);
  };

  const setFilter = (key) => (val) => {
    setFilters((prev) => ({ ...prev, [key]: val }));
    setPage(1);
  };

  return (
    <div className="space-y-3 pb-6">
      {/* ── HEADER ─────────────────────────────────────── */}
      <PageHeader
        title="AI Recommendations"
        subtitle="Cost optimization and architecture proposals generated by the AI engine — requires human approval before any change is applied."
        badge={
          <span className="px-2 py-0.5 rounded-input bg-accent/10 border border-accent/20 text-accent text-[11px] font-semibold">
            {statusCounts['PENDING'] || 0} Pending Review
          </span>
        }
        actions={
          <button
            type="button"
            onClick={refetch}
            disabled={isFetching}
            className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-btn text-xs font-medium bg-surface border border-border text-text hover:bg-bg hover:border-accent transition-colors disabled:opacity-50"
          >
            <RotateCw className={`w-1.5 h-1.5 text-accent ${isFetching ? 'animate-spin' : ''}`} />
            Refresh
          </button>
        }
      />

      {/* ── STATUS COUNT CHIPS ─────────────────────────── */}
      <div className="flex flex-wrap gap-2">
        {STATUS_META.map(({ key, label, icon: Icon, color }) => (
          <button
            key={key}
            type="button"
            onClick={() => setFilter('status')(key)}
            className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-input text-xs font-semibold border transition-all duration-fast focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent ${
              filters.status === key
                ? color + ' ring-1 ring-current/30'
                : 'bg-surface border-border text-textMuted hover:border-accent/40 hover:text-text'
            }`}
            aria-pressed={filters.status === key}
          >
            <Icon className="w-1.5 h-1.5 flex-shrink-0" />
            {label}
            <span className="px-1 py-0.5 rounded text-[10px] bg-black/10 dark:bg-white/10">
              {statusCounts[key] ?? 0}
            </span>
          </button>
        ))}

        {/* Savings summary chip */}
        {filtered.length > 0 && (
          <div className="ml-auto flex items-center gap-1 text-xs text-success font-semibold">
            <CheckCircle2 className="w-1.5 h-1.5" />
            {formatCurrency(totalSavings)}/mo potential savings
          </div>
        )}
      </div>

      {/* ── FILTER BAR ─────────────────────────────────── */}
      <div className="flex flex-wrap gap-2 items-end">
        <div className="flex-1 min-w-[180px]">
          <SearchInput
            value={filters.search}
            onSearch={setFilter('search')}
            placeholder="Search by title, ID, resource..."
            aria-label="Search recommendations"
          />
        </div>
        <Select
          value={filters.category}
          onChange={setFilter('category')}
          options={CATEGORY_OPTIONS}
          className="w-36"
        />
        <Select
          value={filters.risk}
          onChange={setFilter('risk')}
          options={RISK_OPTIONS}
          className="w-32"
        />
        {(filters.category !== 'all' || filters.risk !== 'all' || filters.search) && (
          <button
            type="button"
            onClick={() => { setFilters((p) => ({ ...p, category: 'all', risk: 'all', search: '' })); setPage(1); }}
            className="px-2 py-1.5 text-xs text-textMuted border border-border rounded-btn hover:text-critical hover:border-critical/40 transition-colors"
          >
            Clear filters
          </button>
        )}
      </div>

      {/* ── CONTENT ─────────────────────────────────────── */}
      {isLoading ? (
        <div className="space-y-2">
          {[...Array(4)].map((_, i) => (
            <Skeleton key={i} height={64} variant="rectangular" className="rounded-card" />
          ))}
        </div>
      ) : isError ? (
        <ErrorState
          title="Failed to Load Recommendations"
          message="The AI recommendations service is unavailable. Check your connection and retry."
          onRetry={refetch}
        />
      ) : isMobile ? (
        /* Mobile: card grid */
        filtered.length === 0 ? (
          <div className="p-8 text-center text-xs text-textMuted bg-surface border border-border rounded-card">
            <Search className="w-4 h-4 mx-auto mb-2 text-border" />
            No recommendations match your current filters.
          </div>
        ) : (
          <div className="space-y-2">
            {filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE).map((rec) => (
              <RecommendationCard key={rec.id} rec={rec} onClick={() => handleRowClick(rec)} />
            ))}
            {filtered.length > PAGE_SIZE && (
              <div className="flex justify-center gap-2 pt-1">
                <button
                  disabled={page <= 1}
                  onClick={() => setPage((p) => p - 1)}
                  className="px-2 py-1 text-xs rounded-btn border border-border disabled:opacity-40 hover:border-accent transition-colors"
                >
                  ← Prev
                </button>
                <span className="px-2 py-1 text-xs text-textMuted">
                  {page} / {Math.ceil(filtered.length / PAGE_SIZE)}
                </span>
                <button
                  disabled={page >= Math.ceil(filtered.length / PAGE_SIZE)}
                  onClick={() => setPage((p) => p + 1)}
                  className="px-2 py-1 text-xs rounded-btn border border-border disabled:opacity-40 hover:border-accent transition-colors"
                >
                  Next →
                </button>
              </div>
            )}
          </div>
        )
      ) : (
        /* Desktop: table */
        <RecommendationTable
          recommendations={filtered}
          onRowClick={handleRowClick}
          page={page}
          pageSize={PAGE_SIZE}
          onPageChange={setPage}
        />
      )}

      {/* ── DRAWER ─────────────────────────────────────── */}
      <RecommendationDrawer
        rec={selectedRec}
        isOpen={isDrawerOpen}
        onClose={() => setIsDrawerOpen(false)}
      />
    </div>
  );
}
