/**
 * Mock data for Anomaly Detection incidents covering all 5 severities
 */
export const mockAnomalies = [
  {
    id: 'ANOM-2026-001',
    title: 'Sudden EBS Provisioned IOPS Cost Surge',
    service: 'Amazon EBS',
    resourceId: 'vol-0123456789abcdef0',
    resourceName: 'analytics-primary-storage',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    zScore: 4.8,
    baselineValue: '500 IOPS / $80/mo',
    anomalyValue: '5,000 IOPS / $320/mo',
    deviationPercent: '+300%',
    detectedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    rootCause: 'Batch pipeline script left volume modified at max IOPS tier after daily ingest completed.',
    impactSummary: 'Consuming unnecessary provisioned throughput budget continuously.',
    recommendedActionId: 'REC-002',
  },
  {
    id: 'ANOM-2026-002',
    title: 'Abnormal CPU Throttling in Production Worker Group',
    service: 'Amazon EC2',
    resourceId: 'i-0a8b9c1d2e3f4g5',
    resourceName: 'prod-api-worker-01',
    severity: 'HIGH',
    status: 'ACTIVE',
    zScore: 3.6,
    baselineValue: '18% CPU Utilization',
    anomalyValue: '94% CPU Utilization',
    deviationPercent: '+422%',
    detectedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    rootCause: 'Memory leak triggered garbage collection loop on un-migrated node.',
    impactSummary: 'P99 Latency increased by 180ms.',
    recommendedActionId: 'REC-001',
  },
  {
    id: 'ANOM-2026-003',
    title: 'Unexpected Cross-Region Data Transfer Surge',
    service: 'AWS Data Transfer',
    resourceId: 'vpc-0987654321fedcba',
    resourceName: 'us-east-1-to-eu-west-1',
    severity: 'MEDIUM',
    status: 'INVESTIGATING',
    zScore: 2.7,
    baselineValue: '12 GB/day',
    anomalyValue: '85 GB/day',
    deviationPercent: '+608%',
    detectedAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    rootCause: 'Replication endpoint misconfiguration pushing uncompressed logs across regions.',
    impactSummary: 'Cost impact ~$45/day.',
    recommendedActionId: null,
  },
  {
    id: 'ANOM-2026-004',
    title: 'Lambda Concurrent Execution Spike during Off-Peak',
    service: 'AWS Lambda',
    resourceId: 'fn-payment-processor',
    resourceName: 'payment-webhook-handler',
    severity: 'LOW',
    status: 'RESOLVED',
    zScore: 1.9,
    baselineValue: '15 concurrent invocations',
    anomalyValue: '65 concurrent invocations',
    deviationPercent: '+333%',
    detectedAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    rootCause: 'Third-party gateway retry storm caused by transient webhook 504s.',
    impactSummary: 'Cold start frequency briefly elevated.',
    recommendedActionId: null,
  },
  {
    id: 'ANOM-2026-005',
    title: 'S3 Standard Bucket Access Pattern Shift to Archival',
    service: 'Amazon S3',
    resourceId: 's3-cold-archive-reports',
    resourceName: 'audit-reports-2025-archive',
    severity: 'INFO',
    status: 'RESOLVED',
    zScore: 1.4,
    baselineValue: 'Daily read requests',
    anomalyValue: '0 reads in 60 days',
    deviationPercent: '-100%',
    detectedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    rootCause: 'Files have matured past active retrieval cycle.',
    impactSummary: 'Candidate for S3 Glacier Flexible Transition lifecycle rule.',
    recommendedActionId: 'REC-004',
  },
];

export default mockAnomalies;
