/**
 * Enhanced mock history data with predicted vs actual outcome comparisons.
 * All COMPLETED entries carry both predictedOutcome and actualOutcome blocks.
 */
export const mockHistory = [
  {
    id: 'HIST-001',
    recommendationId: 'REC-004',
    title: 'Transition unaccessed S3 bucket data to S3 Glacier Flexible Retrieval',
    action: 'APPROVED',
    category: 'STORAGE_TIER',
    actor: 'devops-lead@company.internal',
    service: 'Amazon S3',
    resourceId: 's3-cold-archive-reports',
    resourceName: 'audit-reports-2025-archive',
    monthlySavings: 275.48,
    executionStatus: 'COMPLETED',
    timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    executionDetails: 'AWS Lifecycle policy applied successfully. 14.2 TB scheduled for transition on next cycle.',
    durationMs: 1420,
    predictedOutcome: {
      monthlyCost: 51.12,
      monthlySavings: 275.48,
      savingsPercent: 84.3,
      reliabilityImpact: 'None — read-only archive workload, zero app dependency.',
      notes: 'AI confidence: 99%. Transition latency acceptable for compliance tier.',
    },
    actualOutcome: {
      monthlyCost: 49.80,
      monthlySavings: 276.80,
      savingsPercent: 84.7,
      reliabilityImpact: 'Zero incidents. Restore latency tested at 4.1h (within 3–5h SLA).',
      notes: 'Actual cost slightly better than predicted — gzip compression reduced billable size by 0.9%.',
      variance: '+0.5%',          // positive = better than predicted
      varianceDirection: 'better',
    },
    // Monthly cost trend — predicted vs actual over 3 months post-application
    outcomeTimeSeries: [
      { month: 'Before', predicted: 326.60, actual: 326.60 },
      { month: 'Month 1', predicted: 51.12, actual: 49.80 },
      { month: 'Month 2', predicted: 51.12, actual: 48.90 },
      { month: 'Month 3', predicted: 51.12, actual: 47.60 },
    ],
  },
  {
    id: 'HIST-002',
    recommendationId: 'REC-005',
    title: 'Purchase 1-Year Compute Savings Plan for stable baseline compute',
    action: 'REJECTED',
    category: 'SAVINGS_PLAN',
    actor: 'finance-director@company.internal',
    service: 'AWS Compute',
    resourceId: 'sp-baseline-2026',
    resourceName: 'company-compute-savings-plan',
    monthlySavings: 2420.00,
    executionStatus: 'DISMISSED',
    timestamp: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    executionDetails: 'Rejected with rationale: Architectural migration to multi-region serverless pending.',
    durationMs: null,
    predictedOutcome: {
      monthlyCost: 6220.00,
      monthlySavings: 2420.00,
      savingsPercent: 28.0,
      reliabilityImpact: 'None — Savings Plan is a billing construct, not an infrastructure change.',
      notes: 'AI confidence: 88%. Commitment is irreversible.',
    },
    actualOutcome: null, // Rejected — no actual outcome
  },
  {
    id: 'HIST-003',
    recommendationId: 'REC-PREV-012',
    title: 'Delete unattached EBS volumes older than 14 days',
    action: 'APPROVED',
    category: 'STORAGE_TIER',
    actor: 'cloud-admin@company.internal',
    service: 'Amazon EBS',
    resourceId: 'vol-unattached-batch',
    resourceName: 'vol-unattached-batch',
    monthlySavings: 180.00,
    executionStatus: 'COMPLETED',
    timestamp: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    executionDetails: 'Created final snapshots and released 4 dangling gp2 volumes (600 GB).',
    durationMs: 4200,
    predictedOutcome: {
      monthlyCost: 0,
      monthlySavings: 180.00,
      savingsPercent: 100,
      reliabilityImpact: 'None — volumes confirmed detached with no active mount points.',
      notes: 'AI confidence: 97%.',
    },
    actualOutcome: {
      monthlyCost: 0,
      monthlySavings: 180.00,
      savingsPercent: 100,
      reliabilityImpact: 'No incidents. Application health checks nominal post-deletion.',
      notes: 'Exact match with prediction. 4 snapshots archived at $0.05/GB-mo as rollback insurance.',
      variance: '0%',
      varianceDirection: 'exact',
    },
    outcomeTimeSeries: [
      { month: 'Before', predicted: 180.00, actual: 180.00 },
      { month: 'Month 1', predicted: 0, actual: 0 },
      { month: 'Month 2', predicted: 0, actual: 0 },
    ],
  },
  {
    id: 'HIST-004',
    recommendationId: 'REC-PREV-010',
    title: 'Downsize Redis ElastiCache cluster cache.m5.large to cache.t4g.medium',
    action: 'APPROVED',
    category: 'RIGHTSIZING',
    actor: 'sre-oncall@company.internal',
    service: 'Amazon ElastiCache',
    resourceId: 'redis-session-store',
    resourceName: 'redis-session-store',
    monthlySavings: 96.00,
    executionStatus: 'COMPLETED',
    timestamp: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
    executionDetails: 'Seamless replication sync and cluster modification verified.',
    durationMs: 28000,
    predictedOutcome: {
      monthlyCost: 114.00,
      monthlySavings: 96.00,
      savingsPercent: 45.7,
      reliabilityImpact: 'P99 latency expected to increase by ≤2ms under peak load.',
      notes: 'AI confidence: 93%. Graviton3 delivers better single-thread perf for Redis workloads.',
    },
    actualOutcome: {
      monthlyCost: 117.50,
      monthlySavings: 92.50,
      savingsPercent: 44.0,
      reliabilityImpact: 'P99 latency increased by 1.8ms (within predicted ≤2ms bound).',
      notes: 'Savings slightly lower than predicted due to burstable credit top-up during traffic spike on Day 3. Stabilised by Day 7.',
      variance: '-3.6%',
      varianceDirection: 'worse',
    },
    outcomeTimeSeries: [
      { month: 'Before', predicted: 210.00, actual: 210.00 },
      { month: 'Month 1', predicted: 114.00, actual: 117.50 },
      { month: 'Month 2', predicted: 114.00, actual: 115.80 },
      { month: 'Month 3', predicted: 114.00, actual: 114.20 },
    ],
  },
  {
    id: 'HIST-005',
    recommendationId: 'REC-PREV-008',
    title: 'Move CloudFront origin access from public S3 to Origin Access Control (OAC)',
    action: 'APPROVED',
    category: 'ARCH_MODERNIZATION',
    actor: 'security-eng@company.internal',
    service: 'Amazon CloudFront',
    resourceId: 'cf-dist-prod-web',
    resourceName: 'prod-web-cdn',
    monthlySavings: 38.00,
    executionStatus: 'COMPLETED',
    timestamp: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    executionDetails: 'OAC policy deployed. Public bucket ACL revoked. CDN cache invalidation triggered.',
    durationMs: 3100,
    predictedOutcome: {
      monthlyCost: 142.00,
      monthlySavings: 38.00,
      savingsPercent: 21.1,
      reliabilityImpact: 'Improved — removes public S3 bucket exposure. Cache miss rate unchanged.',
      notes: 'AI confidence: 96%. Security posture improvement with minor cost reduction.',
    },
    actualOutcome: {
      monthlyCost: 139.50,
      monthlySavings: 40.50,
      savingsPercent: 22.5,
      reliabilityImpact: 'Improved security posture confirmed. Zero CDN errors. Cache hit rate improved by 1.3%.',
      notes: 'Slightly better savings than predicted. OAC request signing reduced unsigned DataTransfer costs.',
      variance: '+6.6%',
      varianceDirection: 'better',
    },
    outcomeTimeSeries: [
      { month: 'Before', predicted: 180.00, actual: 180.00 },
      { month: 'Month 1', predicted: 142.00, actual: 139.50 },
      { month: 'Month 2', predicted: 142.00, actual: 140.20 },
    ],
  },
];

export default mockHistory;
