/**
 * Mock data for AI Recommendations with human-in-the-loop review metadata
 */
export const mockRecommendations = [
  {
    id: 'REC-001',
    title: 'Downsize over-provisioned EC2 worker cluster from c5.2xlarge to c5.xlarge',
    description: 'Telemetry over the last 30 days indicates peak CPU utilization never exceeded 32% and memory averaged 28%. Downsizing will maintain 2.5x buffer over historical peaks while cutting EC2 hourly compute costs by 50%.',
    service: 'Amazon EC2',
    resourceId: 'i-0a8b9c1d2e3f4g5',
    resourceName: 'prod-api-worker-01',
    category: 'RIGHTSIZING',
    status: 'PENDING', // PENDING | APPROVED | REJECTED
    riskLevel: 'LOW',
    riskScore: 2, // 1 to 10 scale
    confidenceScore: 0.96,
    currentCost: 148.50,
    estimatedCost: 74.25,
    monthlySavings: 74.25,
    annualSavings: 891.00,
    savingsPercent: 50,
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    reviewedAt: null,
    reviewedBy: null,
    architectureDiff: {
      before: {
        instanceType: 'c5.2xlarge',
        vCPUs: 8,
        memoryGiB: 16,
        hourlyRate: '$0.34',
        utilizationAvg: '18% CPU / 28% RAM',
      },
      after: {
        instanceType: 'c5.xlarge',
        vCPUs: 4,
        memoryGiB: 8,
        hourlyRate: '$0.17',
        simulatedUtilizationAvg: '36% CPU / 56% RAM',
      },
    },
    rollbackPlan: 'Instant AMI snapshot rollback via AWS Systems Manager Automation document within 90 seconds if latency exceeds 50ms.',
    aiReasoning: 'Consistent 14-day telemetry baseline confirms compute headroom. Downsizing risk is minimal because workload distributes horizontally via Application Load Balancer.',
  },
  {
    id: 'REC-002',
    title: 'Migrate EBS io2 provisioned volumes to gp3 with custom throughput',
    description: 'Workload requires 3,000 IOPS burst but has steady state of 800 IOPS. Migrating from io2 to gp3 with 3,000 IOPS and 250 MB/s provisioned throughput delivers identical IO latency at 65% lower monthly storage cost.',
    service: 'Amazon EBS',
    resourceId: 'vol-0123456789abcdef0',
    resourceName: 'analytics-primary-storage',
    category: 'STORAGE_TIER',
    status: 'PENDING',
    riskLevel: 'LOW',
    riskScore: 1,
    confidenceScore: 0.98,
    currentCost: 320.00,
    estimatedCost: 98.00,
    monthlySavings: 222.00,
    annualSavings: 2664.00,
    savingsPercent: 69.4,
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    reviewedAt: null,
    reviewedBy: null,
    architectureDiff: {
      before: {
        volumeType: 'io2',
        sizeGiB: 500,
        iops: '5,000 Provisioned',
        throughput: '250 MB/s',
        monthlyRate: '$320.00',
      },
      after: {
        volumeType: 'gp3',
        sizeGiB: 500,
        iops: '3,000 Baseline (Provisioned)',
        throughput: '250 MB/s (Provisioned)',
        monthlyRate: '$98.00',
      },
    },
    rollbackPlan: 'Online volume modification in-place. EBS supports live type conversions with zero downtime.',
    aiReasoning: 'gp3 delivers up to 16,000 IOPS at a fraction of io2 price. Since multi-attach is not enabled on this volume, io2 provisioned premium is unnecessary.',
  },
  {
    id: 'REC-003',
    title: 'Upgrade customer Aurora MySQL cluster to Graviton3 db.r7g instance family',
    description: 'Upgrading from db.r5.2xlarge (x86_64) to db.r7g.2xlarge (Graviton3) delivers up to 20% higher query throughput and 15% lower compute cost.',
    service: 'Amazon RDS',
    resourceId: 'rds-prod-primary-01',
    resourceName: 'customer-aurora-cluster',
    category: 'ARCH_MODERNIZATION',
    status: 'PENDING',
    riskLevel: 'MEDIUM',
    riskScore: 5,
    confidenceScore: 0.91,
    currentCost: 720.00,
    estimatedCost: 610.00,
    monthlySavings: 110.00,
    annualSavings: 1320.00,
    savingsPercent: 15.3,
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    reviewedAt: null,
    reviewedBy: null,
    architectureDiff: {
      before: {
        engine: 'Aurora MySQL 3.04 (Compatible 8.0.28)',
        instanceClass: 'db.r5.2xlarge',
        architecture: 'Intel Xeon Platinum',
        monthlyRate: '$720.00',
      },
      after: {
        engine: 'Aurora MySQL 3.04',
        instanceClass: 'db.r7g.2xlarge',
        architecture: 'AWS Graviton3 ARM',
        monthlyRate: '$610.00',
      },
    },
    rollbackPlan: 'Failover to read replica followed by instance class revert during designated 2-minute maintenance window.',
    aiReasoning: 'Graviton3 exhibits superior DDR5 memory bandwidth benefits for relational database index caching.',
  },
  {
    id: 'REC-004',
    title: 'Transition unaccessed S3 bucket data to S3 Glacier Flexible Retrieval',
    description: '14.2 TB of historical audit logs have had zero read requests in the last 90 days. Creating an automated S3 Lifecycle rule will reduce storage cost from $0.023/GB to $0.0036/GB.',
    service: 'Amazon S3',
    resourceId: 's3-cold-archive-reports',
    resourceName: 'audit-reports-2025-archive',
    category: 'STORAGE_TIER',
    status: 'APPROVED',
    riskLevel: 'LOW',
    riskScore: 1,
    confidenceScore: 0.99,
    currentCost: 326.60,
    estimatedCost: 51.12,
    monthlySavings: 275.48,
    annualSavings: 3305.76,
    savingsPercent: 84.3,
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    reviewedBy: 'devops-lead@company.internal',
    architectureDiff: {
      before: {
        storageClass: 'S3 Standard',
        totalSize: '14.2 TB',
        costPerGB: '$0.023',
        monthlyCost: '$326.60',
      },
      after: {
        storageClass: 'S3 Glacier Flexible',
        totalSize: '14.2 TB',
        costPerGB: '$0.0036',
        monthlyCost: '$51.12',
      },
    },
    rollbackPlan: 'S3 Glacier Restore job initiation (3-5 hour retrieval window).',
    aiReasoning: 'Access logs verify compliance storage status with no active application dependency.',
  },
  {
    id: 'REC-005',
    title: 'Purchase 1-Year Compute Savings Plan for stable baseline compute',
    description: 'Commit to $12.00/hour compute commitment for always-on baseline workloads across EC2, Fargate, and Lambda.',
    service: 'AWS Compute',
    resourceId: 'sp-baseline-2026',
    resourceName: 'company-compute-savings-plan',
    category: 'SAVINGS_PLAN',
    status: 'REJECTED',
    riskLevel: 'HIGH',
    riskScore: 7,
    confidenceScore: 0.88,
    currentCost: 8640.00,
    estimatedCost: 6220.00,
    monthlySavings: 2420.00,
    annualSavings: 29040.00,
    savingsPercent: 28.0,
    createdAt: new Date(Date.now() - 96 * 3600 * 1000).toISOString(),
    reviewedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    reviewedBy: 'finance-director@company.internal',
    rejectionReason: 'Pending architectural migration to multi-region serverless cluster next quarter.',
    architectureDiff: {
      before: {
        paymentOption: '100% On-Demand Compute',
        hourlyCommitment: '$0.00',
      },
      after: {
        paymentOption: '1-Year No Upfront Compute Savings Plan',
        hourlyCommitment: '$12.00/hr',
      },
    },
    rollbackPlan: 'Non-cancellable contract commitment.',
    aiReasoning: 'Workload stability exceeds 85% over 6 months.',
  },
];

export default mockRecommendations;
